// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"poll-app/ent/poll"
	"poll-app/ent/polloption"
	"poll-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PollOptionQuery is the builder for querying PollOption entities.
type PollOptionQuery struct {
	config
	ctx        *QueryContext
	order      []polloption.OrderOption
	inters     []Interceptor
	predicates []predicate.PollOption
	withPoll   *PollQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PollOptionQuery builder.
func (poq *PollOptionQuery) Where(ps ...predicate.PollOption) *PollOptionQuery {
	poq.predicates = append(poq.predicates, ps...)
	return poq
}

// Limit the number of records to be returned by this query.
func (poq *PollOptionQuery) Limit(limit int) *PollOptionQuery {
	poq.ctx.Limit = &limit
	return poq
}

// Offset to start from.
func (poq *PollOptionQuery) Offset(offset int) *PollOptionQuery {
	poq.ctx.Offset = &offset
	return poq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (poq *PollOptionQuery) Unique(unique bool) *PollOptionQuery {
	poq.ctx.Unique = &unique
	return poq
}

// Order specifies how the records should be ordered.
func (poq *PollOptionQuery) Order(o ...polloption.OrderOption) *PollOptionQuery {
	poq.order = append(poq.order, o...)
	return poq
}

// QueryPoll chains the current query on the "poll" edge.
func (poq *PollOptionQuery) QueryPoll() *PollQuery {
	query := (&PollClient{config: poq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := poq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := poq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(polloption.Table, polloption.FieldID, selector),
			sqlgraph.To(poll.Table, poll.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, polloption.PollTable, polloption.PollColumn),
		)
		fromU = sqlgraph.SetNeighbors(poq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PollOption entity from the query.
// Returns a *NotFoundError when no PollOption was found.
func (poq *PollOptionQuery) First(ctx context.Context) (*PollOption, error) {
	nodes, err := poq.Limit(1).All(setContextOp(ctx, poq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{polloption.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (poq *PollOptionQuery) FirstX(ctx context.Context) *PollOption {
	node, err := poq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PollOption ID from the query.
// Returns a *NotFoundError when no PollOption ID was found.
func (poq *PollOptionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = poq.Limit(1).IDs(setContextOp(ctx, poq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{polloption.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (poq *PollOptionQuery) FirstIDX(ctx context.Context) int {
	id, err := poq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PollOption entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PollOption entity is found.
// Returns a *NotFoundError when no PollOption entities are found.
func (poq *PollOptionQuery) Only(ctx context.Context) (*PollOption, error) {
	nodes, err := poq.Limit(2).All(setContextOp(ctx, poq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{polloption.Label}
	default:
		return nil, &NotSingularError{polloption.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (poq *PollOptionQuery) OnlyX(ctx context.Context) *PollOption {
	node, err := poq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PollOption ID in the query.
// Returns a *NotSingularError when more than one PollOption ID is found.
// Returns a *NotFoundError when no entities are found.
func (poq *PollOptionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = poq.Limit(2).IDs(setContextOp(ctx, poq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{polloption.Label}
	default:
		err = &NotSingularError{polloption.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (poq *PollOptionQuery) OnlyIDX(ctx context.Context) int {
	id, err := poq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PollOptions.
func (poq *PollOptionQuery) All(ctx context.Context) ([]*PollOption, error) {
	ctx = setContextOp(ctx, poq.ctx, "All")
	if err := poq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PollOption, *PollOptionQuery]()
	return withInterceptors[[]*PollOption](ctx, poq, qr, poq.inters)
}

// AllX is like All, but panics if an error occurs.
func (poq *PollOptionQuery) AllX(ctx context.Context) []*PollOption {
	nodes, err := poq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PollOption IDs.
func (poq *PollOptionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if poq.ctx.Unique == nil && poq.path != nil {
		poq.Unique(true)
	}
	ctx = setContextOp(ctx, poq.ctx, "IDs")
	if err = poq.Select(polloption.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (poq *PollOptionQuery) IDsX(ctx context.Context) []int {
	ids, err := poq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (poq *PollOptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, poq.ctx, "Count")
	if err := poq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, poq, querierCount[*PollOptionQuery](), poq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (poq *PollOptionQuery) CountX(ctx context.Context) int {
	count, err := poq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (poq *PollOptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, poq.ctx, "Exist")
	switch _, err := poq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (poq *PollOptionQuery) ExistX(ctx context.Context) bool {
	exist, err := poq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PollOptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (poq *PollOptionQuery) Clone() *PollOptionQuery {
	if poq == nil {
		return nil
	}
	return &PollOptionQuery{
		config:     poq.config,
		ctx:        poq.ctx.Clone(),
		order:      append([]polloption.OrderOption{}, poq.order...),
		inters:     append([]Interceptor{}, poq.inters...),
		predicates: append([]predicate.PollOption{}, poq.predicates...),
		withPoll:   poq.withPoll.Clone(),
		// clone intermediate query.
		sql:  poq.sql.Clone(),
		path: poq.path,
	}
}

// WithPoll tells the query-builder to eager-load the nodes that are connected to
// the "poll" edge. The optional arguments are used to configure the query builder of the edge.
func (poq *PollOptionQuery) WithPoll(opts ...func(*PollQuery)) *PollOptionQuery {
	query := (&PollClient{config: poq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	poq.withPoll = query
	return poq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PollOption.Query().
//		GroupBy(polloption.FieldText).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (poq *PollOptionQuery) GroupBy(field string, fields ...string) *PollOptionGroupBy {
	poq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PollOptionGroupBy{build: poq}
	grbuild.flds = &poq.ctx.Fields
	grbuild.label = polloption.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//	}
//
//	client.PollOption.Query().
//		Select(polloption.FieldText).
//		Scan(ctx, &v)
func (poq *PollOptionQuery) Select(fields ...string) *PollOptionSelect {
	poq.ctx.Fields = append(poq.ctx.Fields, fields...)
	sbuild := &PollOptionSelect{PollOptionQuery: poq}
	sbuild.label = polloption.Label
	sbuild.flds, sbuild.scan = &poq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PollOptionSelect configured with the given aggregations.
func (poq *PollOptionQuery) Aggregate(fns ...AggregateFunc) *PollOptionSelect {
	return poq.Select().Aggregate(fns...)
}

func (poq *PollOptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range poq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, poq); err != nil {
				return err
			}
		}
	}
	for _, f := range poq.ctx.Fields {
		if !polloption.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if poq.path != nil {
		prev, err := poq.path(ctx)
		if err != nil {
			return err
		}
		poq.sql = prev
	}
	return nil
}

func (poq *PollOptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PollOption, error) {
	var (
		nodes       = []*PollOption{}
		withFKs     = poq.withFKs
		_spec       = poq.querySpec()
		loadedTypes = [1]bool{
			poq.withPoll != nil,
		}
	)
	if poq.withPoll != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, polloption.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PollOption).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PollOption{config: poq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, poq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := poq.withPoll; query != nil {
		if err := poq.loadPoll(ctx, query, nodes, nil,
			func(n *PollOption, e *Poll) { n.Edges.Poll = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (poq *PollOptionQuery) loadPoll(ctx context.Context, query *PollQuery, nodes []*PollOption, init func(*PollOption), assign func(*PollOption, *Poll)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PollOption)
	for i := range nodes {
		if nodes[i].poll_options == nil {
			continue
		}
		fk := *nodes[i].poll_options
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(poll.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "poll_options" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (poq *PollOptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := poq.querySpec()
	_spec.Node.Columns = poq.ctx.Fields
	if len(poq.ctx.Fields) > 0 {
		_spec.Unique = poq.ctx.Unique != nil && *poq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, poq.driver, _spec)
}

func (poq *PollOptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(polloption.Table, polloption.Columns, sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt))
	_spec.From = poq.sql
	if unique := poq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if poq.path != nil {
		_spec.Unique = true
	}
	if fields := poq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, polloption.FieldID)
		for i := range fields {
			if fields[i] != polloption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := poq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := poq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := poq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := poq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (poq *PollOptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(poq.driver.Dialect())
	t1 := builder.Table(polloption.Table)
	columns := poq.ctx.Fields
	if len(columns) == 0 {
		columns = polloption.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if poq.sql != nil {
		selector = poq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if poq.ctx.Unique != nil && *poq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range poq.predicates {
		p(selector)
	}
	for _, p := range poq.order {
		p(selector)
	}
	if offset := poq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := poq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PollOptionGroupBy is the group-by builder for PollOption entities.
type PollOptionGroupBy struct {
	selector
	build *PollOptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pogb *PollOptionGroupBy) Aggregate(fns ...AggregateFunc) *PollOptionGroupBy {
	pogb.fns = append(pogb.fns, fns...)
	return pogb
}

// Scan applies the selector query and scans the result into the given value.
func (pogb *PollOptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pogb.build.ctx, "GroupBy")
	if err := pogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PollOptionQuery, *PollOptionGroupBy](ctx, pogb.build, pogb, pogb.build.inters, v)
}

func (pogb *PollOptionGroupBy) sqlScan(ctx context.Context, root *PollOptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pogb.fns))
	for _, fn := range pogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pogb.flds)+len(pogb.fns))
		for _, f := range *pogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PollOptionSelect is the builder for selecting fields of PollOption entities.
type PollOptionSelect struct {
	*PollOptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pos *PollOptionSelect) Aggregate(fns ...AggregateFunc) *PollOptionSelect {
	pos.fns = append(pos.fns, fns...)
	return pos
}

// Scan applies the selector query and scans the result into the given value.
func (pos *PollOptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pos.ctx, "Select")
	if err := pos.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PollOptionQuery, *PollOptionSelect](ctx, pos.PollOptionQuery, pos, pos.inters, v)
}

func (pos *PollOptionSelect) sqlScan(ctx context.Context, root *PollOptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pos.fns))
	for _, fn := range pos.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pos.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
