// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PollsColumns holds the columns for the "polls" table.
	PollsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "question", Type: field.TypeString},
		{Name: "created_by", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// PollsTable holds the schema information for the "polls" table.
	PollsTable = &schema.Table{
		Name:       "polls",
		Columns:    PollsColumns,
		PrimaryKey: []*schema.Column{PollsColumns[0]},
	}
	// PollOptionsColumns holds the columns for the "poll_options" table.
	PollOptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "text", Type: field.TypeString},
		{Name: "votes", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "poll_options", Type: field.TypeInt, Nullable: true},
	}
	// PollOptionsTable holds the schema information for the "poll_options" table.
	PollOptionsTable = &schema.Table{
		Name:       "poll_options",
		Columns:    PollOptionsColumns,
		PrimaryKey: []*schema.Column{PollOptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "poll_options_polls_options",
				Columns:    []*schema.Column{PollOptionsColumns[4]},
				RefColumns: []*schema.Column{PollsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VotesColumns holds the columns for the "votes" table.
	VotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "poll_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeString},
		{Name: "option_id", Type: field.TypeInt},
	}
	// VotesTable holds the schema information for the "votes" table.
	VotesTable = &schema.Table{
		Name:       "votes",
		Columns:    VotesColumns,
		PrimaryKey: []*schema.Column{VotesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PollsTable,
		PollOptionsTable,
		UsersTable,
		VotesTable,
	}
)

func init() {
	PollOptionsTable.ForeignKeys[0].RefTable = PollsTable
}
