// Code generated by ent, DO NOT EDIT.

package vote

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the vote type in the database.
	Label = "vote"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPollID holds the string denoting the poll_id field in the database.
	FieldPollID = "poll_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOptionID holds the string denoting the option_id field in the database.
	FieldOptionID = "option_id"
	// Table holds the table name of the vote in the database.
	Table = "votes"
)

// Columns holds all SQL columns for vote fields.
var Columns = []string{
	FieldID,
	FieldPollID,
	FieldUserID,
	FieldOptionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Vote queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPollID orders the results by the poll_id field.
func ByPollID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOptionID orders the results by the option_id field.
func ByOptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOptionID, opts...).ToFunc()
}
